# Generated by Django 2.0 on 2017-12-31 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.IntegerField()),
                ('user', models.OneToOneField(null=True, on_delete='cascade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
