# Generated by Django 2.0 on 2017-12-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserclient',
            name='cid',
            field=models.IntegerField(null=True),
        ),
    ]
