# Generated by Django 2.0 on 2017-12-31 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0003_auto_20171231_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='browserclient',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
