# Generated by Django 2.0 on 2018-01-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spreadsheet', '0004_auto_20171231_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='browserclient',
            name='csv_file',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
